#!/usr/bin/env php
<?php

use Symfony\Component\Console\Output\ConsoleOutput;

define('LARAVEL_START', microtime(true));

// Register the auto-loader
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command
$status = (require __DIR__.'/bootstrap/app.php')
    ->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
